/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '"Space Grotesk"', 'system-ui', 'sans-serif'],
        display: ['"Syne"', '"Space Grotesk"', 'sans-serif'],
        serif: ['"Instrument Serif"', '"DM Serif Display"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        zeyada: ['"Zeyada"', 'cursive'],
      },
      colors: {
        bg: 'var(--bg)',
        panel: 'var(--panel)',
        'panel-sub': 'var(--panel-sub)',
        'panel-card': 'var(--panel-card)',
        border: 'var(--border)',
        'border-soft': 'var(--border-soft)',
        'border-brass': 'var(--border-brass)',
        text: 'var(--text)',
        'text-dim': 'var(--text-dim)',
        'text-faint': 'var(--text-faint)',
        'parchment': 'var(--parchment)',
        'orange-1': 'var(--orange-1)',
        'orange-2': 'var(--orange-2)',
        'orange-3': 'var(--orange-3)',
        'orange-4': 'var(--orange-4)',
        'amber-1': 'var(--amber-1)',
        'amber-2': 'var(--amber-2)',
        'amber-3': 'var(--amber-3)',
        'amber-glow-color': 'var(--amber-glow-color)',
        'crimson-1': 'var(--crimson-1)',
        'crimson-2': 'var(--crimson-2)',
        'crimson-deep': 'var(--crimson-deep)',
        'phosphor-green': 'var(--phosphor-green)',
      },
      boxShadow: {
        'clean-card': '0 4px 25px -2px rgba(0, 0, 0, 0.25), 0 2px 8px -1px rgba(0, 0, 0, 0.15)',
        'clean-hover': '0 20px 40px -4px rgba(0, 0, 0, 0.4), 0 10px 20px -3px rgba(0, 0, 0, 0.2)',
        'orange-glow': '0 0 30px rgba(255, 170, 43, 0.35)',
        'amber-glow': '0 0 35px rgba(255, 170, 43, 0.4)',
        'crimson-glow': '0 0 35px rgba(255, 42, 95, 0.35)',
        'crt-bloom': '0 0 15px rgba(255, 170, 43, 0.15), inset 0 0 15px rgba(255, 170, 43, 0.05)',
        'retro-bevel': 'inset 1px 1px 0 rgba(255, 255, 255, 0.1), inset -1px -1px 0 rgba(0, 0, 0, 0.4)',
      },
      backgroundImage: {
        'jazz-gradient': 'radial-gradient(ellipse at top, var(--panel-sub) 0%, var(--bg) 80%)',
        'spotlight-beam': 'conic-gradient(from 225deg at 50% 0%, rgba(255,170,43,0.08) 0deg, rgba(255,42,95,0.05) 45deg, transparent 90deg)',
      },
    },
  },
  plugins: [],
}